[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
    refreshPeriod = "168h"
    clone = {args = ["--depth=1"]}
    pull = {args = ["--ff-only"]}
